/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesconsultas;

import conexiones.MySqlConn;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Adrian Quinn
 */
public class FrameConsultaPorMes extends javax.swing.JInternalFrame {
    MySqlConn conn=new MySqlConn();
    int meses[]=new int[12];
    
    /**
     * Creates new form FrameConsultaPorMes
     */
    public FrameConsultaPorMes() {
        initComponents();
        limpiarVector();
        obtenerMeses();
        generarGrafica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTipoConsulta = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jPanelBarras = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulo.setBackground(new java.awt.Color(102, 255, 204));
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTipoConsulta.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabelTipoConsulta.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTipoConsulta.setText("PERSONAS HOSPEDADAS POR MES");
        jPanelTitulo.add(jLabelTipoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 140));

        jPanelFondo.setBackground(new java.awt.Color(51, 51, 51));

        jPanelBarras.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelBarrasLayout = new javax.swing.GroupLayout(jPanelBarras);
        jPanelBarras.setLayout(jPanelBarrasLayout);
        jPanelBarrasLayout.setHorizontalGroup(
            jPanelBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        jPanelBarrasLayout.setVerticalGroup(
            jPanelBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1020, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTipoConsulta;
    private javax.swing.JPanel jPanelBarras;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables

    
    public void limpiarVector(){
        //Lllenar el vector de 0
        for (int i = 0; i < 12; i++) {
            this.meses[i]=0;
        }
    }
    
    public void obtenerMeses(){
        
        String query="select * from huespedes";
        Calendar calendario=Calendar.getInstance();
        int mes=0;
        Date aux=null;
        
        
        this.conn.Consult(query);
        //Recorro todas las row de la base para obtener su mes y sumar en sus respectiva posicion
        //del mes
        try{
            this.conn.rs.last();
            int total=this.conn.rs.getRow();
            this.conn.rs.first();
            for (int i = 0; i < total-1; i++) {
                aux=this.conn.rs.getDate(6);
                calendario.setTime(aux);
                mes=calendario.get(Calendar.MONTH);
                mes++;
                System.out.println(mes);
                switch(mes){
                    case 1: this.meses[0]++;
                            break;
                    case 2: this.meses[1]++;
                            break;
                    case 3: this.meses[2]++;
                            break;
                    case 4: this.meses[3]++;
                            break;
                    case 5: this.meses[4]++;
                            break;
                    case 6: this.meses[5]++;
                            break;
                    case 7: this.meses[6]++;
                            break;
                    case 8: this.meses[7]++;
                            break;
                    case 9: this.meses[8]++;
                            break;
                    case 10: this.meses[9]++;
                            break;
                    case 11: this.meses[10]++;
                            break;
                    case 12: this.meses[11]++;
                            break;      
  
                }
                this.conn.rs.next();
            }
                aux=this.conn.rs.getDate(6);
                calendario.setTime(aux);
                mes=calendario.get(Calendar.MONTH);
                mes++;
                switch(mes){
                    case 1: this.meses[0]++;
                            break;
                    case 2: this.meses[1]++;
                            break;
                    case 3: this.meses[2]++;
                            break;
                    case 4: this.meses[3]++;
                            break;
                    case 5: this.meses[4]++;
                            break;
                    case 6: this.meses[5]++;
                            break;
                    case 7: this.meses[6]++;
                            break;
                    case 8: this.meses[7]++;
                            break;
                    case 9: this.meses[8]++;
                            break;
                    case 10: this.meses[9]++;
                            break;
                    case 11: this.meses[10]++;
                            break;
                    case 12: this.meses[11]++;
                            break;      
  
                }
            
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "No se logro la consulta");
        }
        
        
    
    
    
    }
    
    public void generarGrafica(){
        //Ya qeu se cuenta con la informacion, se pasan los datos para generar la grafica
        DefaultCategoryDataset datos=new DefaultCategoryDataset();
        
        datos.setValue(this.meses[0], "Huespedes", "Enero");
        datos.setValue(this.meses[1], "Huespedes", "Febrero");
        datos.setValue(this.meses[2], "Huespedes", "Marzo");
        datos.setValue(this.meses[3], "Huespedes", "Abril");
        datos.setValue(this.meses[4], "Huespedes", "Mayo");
        datos.setValue(this.meses[5], "Huespedes", "Junio");
        datos.setValue(this.meses[6], "Huespedes", "Julio");
        datos.setValue(this.meses[7], "Huespedes", "Agosto");
        datos.setValue(this.meses[8], "Huespedes", "Septiembre");
        datos.setValue(this.meses[9], "Huespedes", "Octubre");
        datos.setValue(this.meses[10], "Huespedes", "Noviembre");
        datos.setValue(this.meses[11], "Huespedes", "Diciembre");
                
        
        JFreeChart graficoBarras=ChartFactory.createBarChart3D(
        "Cantidad de huespedes por Mes\n Yummy Resorts",  //nombre de la grafica
        "Meses", //nombre de las barras o culmanas
        "Cantidad de huespedes",   //nombre de la numeracion
        datos, //datos del grafico
        PlotOrientation.VERTICAL, //orientacion
        true, //leyenda de barras individuales por oclor
        true,  //herramientas
        false   //url del grafico
        );
        
        ChartPanel panel=new ChartPanel(graficoBarras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(999,400));
        
        jPanelBarras.setLayout(new BorderLayout());
        jPanelBarras.add(panel,BorderLayout.CENTER);
        
        pack();
        repaint();
        
    
    
    }

}
