/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesconsultas;

import conexiones.MySqlConn;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar Daniel
 */
public class FrameHabitacionesDisponibles extends javax.swing.JInternalFrame {

    MySqlConn conn = new MySqlConn();

    /**
     * Creates new form FrameHabitacionesDisponibles
     */
    public FrameHabitacionesDisponibles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelFondoTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFondoPrincipal = new javax.swing.JPanel();
        jRadioButtonPiso1 = new javax.swing.JRadioButton();
        jRadioButtonPiso2 = new javax.swing.JRadioButton();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInformacion = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoTitulo.setBackground(new java.awt.Color(81, 243, 109));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("HABITACIONES DISPONIBLES");

        javax.swing.GroupLayout jPanelFondoTituloLayout = new javax.swing.GroupLayout(jPanelFondoTitulo);
        jPanelFondoTitulo.setLayout(jPanelFondoTituloLayout);
        jPanelFondoTituloLayout.setHorizontalGroup(
            jPanelFondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoTituloLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanelFondoTituloLayout.setVerticalGroup(
            jPanelFondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoTituloLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelFondoPrincipal.setBackground(new java.awt.Color(132, 191, 191));
        jPanelFondoPrincipal.setForeground(new java.awt.Color(153, 153, 153));
        jPanelFondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButtonPiso1);
        jRadioButtonPiso1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButtonPiso1.setText("PISO 1");
        jPanelFondoPrincipal.add(jRadioButtonPiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, -1));

        buttonGroup1.add(jRadioButtonPiso2);
        jRadioButtonPiso2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButtonPiso2.setText("PISO 2");
        jPanelFondoPrincipal.add(jRadioButtonPiso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));

        jButtonConfirmar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanelFondoPrincipal.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 170, 80));

        jTextAreaInformacion.setColumns(20);
        jTextAreaInformacion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInformacion);

        jPanelFondoPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 370, 360));

        getContentPane().add(jPanelFondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1010, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:

        if (this.jRadioButtonPiso1.isSelected()) {
            consultarHab(126, 109);
        } else if (this.jRadioButtonPiso2.isSelected()) {
            consultarHab(146, 128);

        }


    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFondoPrincipal;
    private javax.swing.JPanel jPanelFondoTitulo;
    private javax.swing.JRadioButton jRadioButtonPiso1;
    private javax.swing.JRadioButton jRadioButtonPiso2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInformacion;
    // End of variables declaration//GEN-END:variables

    public void consultarHab(int limiteSup, int limiteInf) {
        String query = "select * from habitaciones";
        ArrayList<String> sencillas = new ArrayList();
        ArrayList<String> dobles = new ArrayList();
        ArrayList<String> master = new ArrayList();
        this.conn.Consult(query);
        if (limiteSup == 126) {
            try {

                this.conn.rs.first();

                for (int i = 0; i < 15; i++) {
                    if (this.conn.rs.getBoolean(2) == false) {
                        if (this.conn.rs.getString(3) == "Sencilla") {
                            int aux = this.conn.rs.getInt(1);
                            sencillas.add(String.valueOf(aux));
                        } else if (this.conn.rs.getString(3) == "Dual") {
                            int aux = this.conn.rs.getInt(1);
                            dobles.add(String.valueOf(aux));
                        } else if (this.conn.rs.getString(3) == "Master") {
                            int aux = this.conn.rs.getInt(1);
                            master.add(String.valueOf(aux));
                        }

                    }
                    this.conn.rs.next();

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No fue posible acceder a la base");

            }
        } else if (limiteSup == 146) {
            try {
                this.conn.rs.first();
                for (int i = 0; i < 15; i++) {
                    this.conn.rs.next();
                }
                for (int i = 0; i < 15; i++) {
                    if (this.conn.rs.getBoolean(2) == false) {
                        if (this.conn.rs.getString(3) == "Sencilla") {
                            int aux = this.conn.rs.getInt(1);
                            sencillas.add(String.valueOf(aux));
                        } else if (this.conn.rs.getString(3) == "Dual") {
                            int aux = this.conn.rs.getInt(1);
                            dobles.add(String.valueOf(aux));
                        } else if (this.conn.rs.getString(3) == "Master") {
                            int aux = this.conn.rs.getInt(1);
                            master.add(String.valueOf(aux));
                        }

                    }
                    this.conn.rs.next();

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No fue posible acceder a la base");

            }
             String mensaje="En el piso 2 estan disponibles:\n" + "Sencillas: ";
             for (int i = 0; i < sencillas.size(); i++) {
                 String aux = sencillas.get(i);
                 mensaje.concat(aux);   
            }
             mensaje.concat("\nDual: ");
             for (int i = 0; i < dobles.size() ; i++) {
                 String aux = dobles.get(i);
                 mensaje.concat(aux);   
            }
             mensaje.concat("\nMaster: ");
             for (int i = 0; i < master.size(); i++) {
                 String aux = master.get(i);
                 mensaje.concat(aux);       
            }
             this.jTextAreaInformacion.setText(mensaje);
        }
       
    }
}

    
