/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesconsultas;

import conexiones.MySqlConn;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import misclases.SClip;

/**
 *
 * @author Jesús
 */
public class FrameGaleriaFotos extends javax.swing.JInternalFrame {

    MySqlConn conn = new MySqlConn();
    public SClip music = new SClip("src/musica/Nora.wav");

    /**
     * Creates new form FramePrueba
     */
    public FrameGaleriaFotos() {
        initComponents();
        music.play();
        icono();
        GenerarImagen();
        Logo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPlay = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonSig = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jLabelImage1 = new javax.swing.JLabel();
        jLabelImage2 = new javax.swing.JLabel();
        jLabelImage3 = new javax.swing.JLabel();
        jLabelImage4 = new javax.swing.JLabel();
        jLabelImage5 = new javax.swing.JLabel();
        JLabelLogo = new javax.swing.JLabel();
        jLabelImagenes = new javax.swing.JLabel();
        jLabelMusica = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelCerrarEtiqueta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPlay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonPlay.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPlay.setText("Play");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 160, 50));

        jButtonStop.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonStop.setForeground(new java.awt.Color(0, 0, 0));
        jButtonStop.setText("Stop");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 160, 50));

        jButtonSig.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSig.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSig.setText("Siguientes");
        jButtonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSigActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 160, 50));

        jButtonAnt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAnt.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnt.setText("Anteriores");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 160, 50));
        getContentPane().add(jLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 150));
        getContentPane().add(jLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 200, 150));
        getContentPane().add(jLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 200, 150));
        getContentPane().add(jLabelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 200, 150));
        getContentPane().add(jLabelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 200, 150));
        getContentPane().add(JLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 250, 200));

        jLabelImagenes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelImagenes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImagenes.setText("Imágenes del Hotel");
        getContentPane().add(jLabelImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabelMusica.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelMusica.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMusica.setText("Música");
        getContentPane().add(jLabelMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jPanel12.setBackground(new java.awt.Color(102, 255, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        jPanel12.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 40, 40));

        jLabelCerrarEtiqueta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCerrarEtiqueta.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCerrarEtiqueta.setText("Cerrar");
        jPanel12.add(jLabelCerrarEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, -1, -1));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1050, 270));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        music.stop();
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        music.play();
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigActionPerformed
        GenerarImagen2();
    }//GEN-LAST:event_jButtonSigActionPerformed

    private void jButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        GenerarImagen();
    }//GEN-LAST:event_jButtonAntActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked

        music.stop();
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    public void GenerarImagen() {
        //Obtenemos las imagenes desde nuestra base de datos
        String query = "select * from imagenes";
        InputStream in;
        this.conn.Consult(query);
        try {
            for (int i = 0; i < 5; i++) {
                //Se obtienen las imagenes y se distribuyen segun i en las labels
                byte[] bi = this.conn.rs.getBytes(2);
                BufferedImage image = null;
                in = new ByteArrayInputStream(bi);
                image = ImageIO.read(in);
                ImageIcon imgi = new ImageIcon(image.getScaledInstance(250, 200, 0));
                switch (i) {
                    case 0:
                        this.jLabelImage1.setIcon(imgi);
                        break;
                    case 1:
                        this.jLabelImage2.setIcon(imgi);
                        break;
                    case 2:
                        this.jLabelImage3.setIcon(imgi);
                        break;
                    case 3:
                        this.jLabelImage4.setIcon(imgi);
                        break;
                    case 4:
                        this.jLabelImage5.setIcon(imgi);
                        break;
                }
                this.conn.rs.next();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No fue posible hacer la consulta");
        } catch (IOException p) {
            JOptionPane.showMessageDialog(null, "No fue posible hacer la consulta");
        }
    }

    public void GenerarImagen2() {
        //Se realizar el mismo proceso, pero esta ocasion para la segunda pagina
        //se brincan las 5 primeras imagenes en el switch
        String query = "select * from imagenes";
        InputStream in;
        this.conn.Consult(query);
        try {
            for (int i = 0; i < 10; i++) {
                byte[] bi = this.conn.rs.getBytes(2);
                BufferedImage image = null;
                in = new ByteArrayInputStream(bi);
                image = ImageIO.read(in);
                ImageIcon imgi = new ImageIcon(image.getScaledInstance(250, 200, 0));
                switch (i) {
                    case 5:
                        this.jLabelImage1.setIcon(imgi);
                        break;
                    case 6:
                        this.jLabelImage2.setIcon(imgi);
                        break;
                    case 7:
                        this.jLabelImage3.setIcon(imgi);
                        break;
                    case 8:
                        this.jLabelImage4.setIcon(imgi);
                        break;
                    case 9:
                        this.jLabelImage5.setIcon(imgi);
                        break;
                }
                this.conn.rs.next();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No fue posible hacer la consulta");
        } catch (IOException p) {
            JOptionPane.showMessageDialog(null, "No fue posible hacer la consulta");
        }
    }

    public void Logo() {
        this.JLabelLogo.setIcon(new ImageIcon("src/imagenes/yummy2.png"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLogo;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonSig;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelCerrarEtiqueta;
    private javax.swing.JLabel jLabelImage1;
    private javax.swing.JLabel jLabelImage2;
    private javax.swing.JLabel jLabelImage3;
    private javax.swing.JLabel jLabelImage4;
    private javax.swing.JLabel jLabelImage5;
    private javax.swing.JLabel jLabelImagenes;
    private javax.swing.JLabel jLabelMusica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    // End of variables declaration//GEN-END:variables
    public void icono() {
        ImageIcon cerrar = new ImageIcon("src/iconos/cancel.png");
        this.jLabelCerrar.setIcon(cerrar);
    }

}
