/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author cabe_
 */
public class Presentacion extends javax.swing.JFrame {

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presentacion");
        setBounds(new java.awt.Rectangle(720, 720, 720, 720));
        setLocation(new java.awt.Point(150, 0));
        setMaximumSize(new java.awt.Dimension(720, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonEntrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEntrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 140, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SesionLogin().setVisible(true);
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g){
         super.paint(g);
         ImageIcon iconoSalir=new ImageIcon("src/iconos/enter.png");
         //g.setColor(Color.red);
         //g.drawLine(0,70,100,70);
         Toolkit t3 = Toolkit.getDefaultToolkit ();
         Image imagen3 = t3.getImage("src/imagenes/fondopresentacion.png");
         g.drawImage(imagen3, 0, 0, this);
         Font fuente=new Font(Font.SANS_SERIF,Font.BOLD,18);
         
         Toolkit t = Toolkit.getDefaultToolkit ();
         Image imagen = t.getImage("src/imagenes/LOGOBENEMERITA_CIRCULAR2.png");
         g.drawImage(imagen, 315, 80, this);
         
         Toolkit t2 = Toolkit.getDefaultToolkit ();
         Image imagen2 = t.getImage("src/imagenes/barrasesquina2.png");
         g.drawImage(imagen2, 0, 0, this);
         
         g.setColor(Color.WHITE);
         g.setFont(fuente);
         g.drawString("Materia: Programacion II", 230, 280);
         g.drawString("Maestra: Georgina Salazar Partida", 230, 310);
         g.drawString("Fecha Entrega: 16/06/2021",230,340);
         g.drawString("Integrantes:", 330, 380);
         g.drawString("Rivera Sanchez Abraham Alejandro ID: 269385", 230, 410);
         g.drawString("Marquez Ortiz Adrian ID: 271927", 230, 440);
         g.drawString("Ruiz Contreras Jesus ID: 270375", 230, 470);
         g.drawString("Aguila Urzua Cesar Daniel ID: 222245", 230, 500);
         this.jButtonEntrar.setIcon(iconoSalir);
              

         //this.jLabelSalir.setIcon(iconoSalir);
    }

}
