/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import conexiones.MySqlConn;
import java.sql.Date;
import java.sql.SQLException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.Period;
import java.util.Scanner;
import javax.swing.ImageIcon;


/**
 *
 * @author Adrian Quinn
 */
public class ServicioCheckOut extends javax.swing.JFrame {

    String nombreHuesped = "";
    String cdOrigen = "";
    Date fechaIngreso;
    Date fechaSalida;
    String tipodeHab = "";
    int Costohab = 0;
    int diasUsados = 0;
    int Totalsc = 0;
    int Totalce = 0;
    String servicios = "";
    MySqlConn conn = new MySqlConn();
    String user = "";

    /**
     * Creates new form ServicioCheckOut
     */
    public ServicioCheckOut() {
        initComponents();
        cargarIconos();
    }

    public ServicioCheckOut(String usuario) {
        initComponents();
        this.user = usuario;
        cargarIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHab = new javax.swing.JTextField();
        jCheckBoxAlcuarto = new javax.swing.JCheckBox();
        jCheckBoxBar = new javax.swing.JCheckBox();
        jCheckBoxTintoreria = new javax.swing.JCheckBox();
        jCheckBoxSPA = new javax.swing.JCheckBox();
        jCheckBoxGuarderia = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonIngresar = new javax.swing.JButton();
        jButtonGenerarCobro = new javax.swing.JButton();
        jLabelBackMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelLogoUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese el Numero de Habitacion que realiza su CheckOut");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTextFieldHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHabActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 30));

        jCheckBoxAlcuarto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxAlcuarto.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxAlcuarto.setText("Servicio al Cuarto");
        jCheckBoxAlcuarto.setContentAreaFilled(false);
        jPanel1.add(jCheckBoxAlcuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jCheckBoxBar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxBar.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxBar.setText("Bar");
        jCheckBoxBar.setContentAreaFilled(false);
        jPanel1.add(jCheckBoxBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jCheckBoxTintoreria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxTintoreria.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTintoreria.setText("Tintoreria");
        jCheckBoxTintoreria.setContentAreaFilled(false);
        jPanel1.add(jCheckBoxTintoreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jCheckBoxSPA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxSPA.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSPA.setText("SPA");
        jCheckBoxSPA.setContentAreaFilled(false);
        jPanel1.add(jCheckBoxSPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jCheckBoxGuarderia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBoxGuarderia.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxGuarderia.setText("Guarderia");
        jCheckBoxGuarderia.setContentAreaFilled(false);
        jPanel1.add(jCheckBoxGuarderia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ticket", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jTextArea1.setCaretColor(new java.awt.Color(255, 0, 204));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 403, 288));

        jButtonIngresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 79, -1, -1));

        jButtonGenerarCobro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonGenerarCobro.setForeground(new java.awt.Color(0, 153, 153));
        jButtonGenerarCobro.setText("Generar Cobro");
        jButtonGenerarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarCobroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerarCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 467, -1, -1));

        jLabelBackMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMenuMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelBackMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 60, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MENU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, -4, 740, 530));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        jLabelNomUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNomUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomUsuario.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grieta de la Orden 687, Calvillo,AGS.");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotel Yummy Resorts");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelLogoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(jLabelNomUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel6))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelLogoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMenuMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MenuHotel(this.user).setVisible(true);
    }//GEN-LAST:event_jLabelBackMenuMouseClicked

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        String cadena1 = "select * from huespedes where habitacion = " + "'" + this.jTextFieldHab.getText().trim() + "'";
        String tipodehab = "";
        int hab = 0;
        int personas = 0;
        int costo = 0;

        this.conn.Consult(cadena1);

        //Aqui ingresamos a la base de datos para sacar la informacion correspondiente
        try {
            this.jTextArea1.setText("");
            this.nombreHuesped = this.conn.rs.getString(1);
            this.cdOrigen = this.conn.rs.getString(2);
            this.fechaIngreso = this.conn.rs.getDate(6);
            this.fechaSalida = this.conn.rs.getDate(7);
            personas = this.conn.rs.getInt(5);
            costo = this.conn.rs.getInt(8);
            tipodehab = this.conn.rs.getString(4);
            hab = this.conn.rs.getInt(3);
            this.tipodeHab = tipodehab;
            this.Costohab = costo;
            this.Totalsc = costo;
            this.jTextArea1.append("Se reservo habitacion " + tipodehab + "\n");
            this.jTextArea1.append("Costo " + "                                   $" + costo);
            this.jTextArea1.append("\n");

            //Checamos que tipo de habitacion para asi generar un costo extra
            switch (tipodehab) {
                case "Sencilla":
                    if (personas > 1) {
                        personas--;
                        costo += personas * 180;
                        this.jTextArea1.append(personas + " Persona Extra                  $180\n");
                    }
                    break;
                case "Dual":
                    if (personas > 2) {
                        personas = personas - 2;
                        costo += personas * 180;
                        this.jTextArea1.append(personas + " Persona Extra                  $180\n");
                    }
                    break;
                case "Master":
                    if (personas > 3) {
                        personas = personas - 3;
                        costo += personas * 180;
                        this.jTextArea1.append(personas + " Persona Extra                  $180\n");
                    }
                    break;
            }

            /*if(tipodehab=="Sencilla"){
                hab=1;
            }else if(tipodehab=="Dual"){
                hab=2;
            }else if(tipodehab=="Master"){
                hab=3;
            }*/
            //Vemos que servicios adicionales ocupo
            if (this.jCheckBoxAlcuarto.isSelected()) {
                this.jTextArea1.append("Servico al cuarto                   $100");
                this.servicios = this.servicios + "Servicio al cuarto            $100\n";
                costo = costo + 100;
                this.jTextArea1.append("\n");
            }
            if (this.jCheckBoxBar.isSelected()) {
                this.jTextArea1.append("Servico de bar                        $250");
                this.servicios = this.servicios + "Servicio de bar                $250\n";
                costo = costo + 250;
                this.jTextArea1.append("\n");
            }
            if (this.jCheckBoxGuarderia.isSelected()) {
                this.jTextArea1.append("Servico de Guarderia            $150");
                this.servicios = this.servicios + "Servicio de Guarderia           $150\n";
                costo = costo + 150;
                this.jTextArea1.append("\n");
            }
            if (this.jCheckBoxSPA.isSelected()) {
                this.jTextArea1.append("Servico de SPA                     $350");
                this.servicios = this.servicios + "Servicio de Spa                 $350\n";
                costo = costo + 350;
                this.jTextArea1.append("\n");
            }
            if (this.jCheckBoxTintoreria.isSelected()) {
                this.jTextArea1.append("Servico de tintoreria              $185");
                this.servicios = this.servicios + "Servicio de Tintoreria                $185\n";
                costo = costo + 185;
                this.jTextArea1.append("\n");
            }

            this.jTextArea1.append("\nEl costo total sera de         $" + costo);

            this.Totalce = costo;
            System.out.println(this.servicios);

        } catch (SQLException ex) {
            System.out.println("No existe");
        }

        System.out.println(personas);
        System.out.println(costo);

        //Aqui vamos a la tabla de ingresos totales del hotel
        String query = "select * from hotelinfo";
        String query2 = "";
        String query3 = "";
        int ingresos = 0;

        this.conn.Consult(query);

        try {
            ingresos = this.conn.rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("No se puede acceder");
        }

        //Eliminamos los ingresos anteriores para añadir los nuevos
        query3 = "delete from hotelinfo where ingresosGenerados = " + ingresos;
        int i = this.conn.Update(query3);
        if (i > 0) {
            System.out.println("Eliminado con exito");
        } else {
            System.out.println("Fallo de eliminacion");
        }

        ingresos = ingresos + costo;
        query2 = "insert into hotelinfo (ingresosGenerados) values (" + "'" + ingresos + "')";

        int j = this.conn.Update(query2);
        System.out.println(ingresos);

        //Eliminamos al huesped que se dio de baja
        String queryHuespedes = "delete from huespedes where habitacion = " + hab;
        int w = this.conn.Update(queryHuespedes);
        if (w > 0) {
            System.out.println("Eliminado con exito (Huespedes)");
        } else {
            System.out.println("Fallo de eliminacion (Huespedes)");
        }
        
        //Aqui regresamos la habitacion a disponible en la base de datos
        String queryHab="update habitaciones set estado = 0 where numero = "+hab;
        int f = this.conn.Update(queryHab);
        if (f > 0) {
            System.out.println("Actualizado con exito");
        } else {
            System.out.println("No se actualizo la habitacion");
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jTextFieldHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHabActionPerformed

    private void jButtonGenerarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarCobroActionPerformed
        // TODO add your handling code here:
        Duration diff = Duration.between(this.fechaIngreso.toLocalDate().atStartOfDay(), this.fechaSalida.toLocalDate().atStartOfDay());
        Period period = Period.between(this.fechaIngreso.toLocalDate(), this.fechaSalida.toLocalDate());
        this.diasUsados = (int) diff.toDays();
        System.out.println("Dias usados: " + this.diasUsados);
        GenerarPDF pdf = new GenerarPDF(nombreHuesped, cdOrigen, fechaIngreso, fechaSalida, tipodeHab, Costohab, diasUsados, Totalsc, Totalce, servicios);
        pdf.prubeaPdf();
    }//GEN-LAST:event_jButtonGenerarCobroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicioCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicioCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicioCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicioCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicioCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonGenerarCobro;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JCheckBox jCheckBoxAlcuarto;
    private javax.swing.JCheckBox jCheckBoxBar;
    private javax.swing.JCheckBox jCheckBoxGuarderia;
    private javax.swing.JCheckBox jCheckBoxSPA;
    private javax.swing.JCheckBox jCheckBoxTintoreria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBackMenu;
    private javax.swing.JLabel jLabelLogoUsuario;
    private javax.swing.JLabel jLabelNomUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldHab;
    // End of variables declaration//GEN-END:variables
    
    public void cargarIconos() {
        ImageIcon adrian = new ImageIcon("src/iconos/adrian.png");
        ImageIcon alex = new ImageIcon("src/iconos/alex.png");
        ImageIcon cesar = new ImageIcon("src/iconos/cesar.png");
        ImageIcon jesus = new ImageIcon("src/iconos/jesus.png");
        ImageIcon logousuario=new ImageIcon("src/iconos/user.png");
        ImageIcon menuIcono=new ImageIcon("src/iconos/menu_1.png");
        ImageIcon fondo=new ImageIcon("src/imagenes/fondocheckout.png");
        ImageIcon iconoBotonIng=new ImageIcon("src/iconos/loupe.png");
        ImageIcon iconoBotonTicket=new ImageIcon("src/iconos/check.png");
        
        this.jLabelBackMenu.setIcon(menuIcono);
        this.fondo.setIcon(fondo);
        this.jButtonGenerarCobro.setIcon(iconoBotonTicket);
        this.jButtonIngresar.setIcon(iconoBotonIng);

        this.jLabelNomUsuario.setText(this.user);
        if (this.user.equals("Adrian")) {
            this.jLabelLogoUsuario.setIcon(adrian);
        } else if (this.user.equals("Alejandro")) {
            this.jLabelLogoUsuario.setIcon(alex);
        } else if (this.user.equals("Cesar")) {
            this.jLabelLogoUsuario.setIcon(cesar);
        } else if (this.user.equals("Jesus")) {
            this.jLabelLogoUsuario.setIcon(jesus);
        } else {
            this.jLabelLogoUsuario.setIcon(logousuario);
        }
    }

}


