/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import conexiones.MySqlConn;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Adrian Quinn
 */
public class SesionLogin extends javax.swing.JFrame {
    MySqlConn conn=new MySqlConn();
    /**
     * Creates new form SesionLogin
     */
    public SesionLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        carga_iconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelHotel = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelIconoGrandeUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelCandadoIco = new javax.swing.JLabel();
        jLabelIconoLog = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPasswordContraUsuario = new javax.swing.JPasswordField();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(68, 251, 201));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHotel.setPreferredSize(new java.awt.Dimension(235, 234));
        jPanel2.add(jLabelHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabelInfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseMoved(evt);
            }
        });
        jLabelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseExited(evt);
            }
        });
        jPanel2.add(jLabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 456, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabelIconoGrandeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 130));

        jSeparator1.setBackground(new java.awt.Color(60, 246, 184));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 180, 10));

        jSeparator2.setBackground(new java.awt.Color(60, 246, 184));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, 10));

        jTextFieldUsuario.setBackground(new java.awt.Color(248, 248, 248));
        jTextFieldUsuario.setText("Introduzca su usuario");
        jTextFieldUsuario.setToolTipText("Introduzca su usuario");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsuarioMouseClicked(evt);
            }
        });
        jPanel4.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 180, 20));

        jLabelCandadoIco.setText(" ");
        jPanel4.add(jLabelCandadoIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 40, 40));

        jLabelIconoLog.setText(" ");
        jPanel4.add(jLabelIconoLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 40, 40));

        jButtonLogin.setBackground(new java.awt.Color(248, 248, 248));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLogin.setText("Login");
        jButtonLogin.setBorder(null);
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, 40));

        jPasswordContraUsuario.setBackground(new java.awt.Color(248, 248, 248));
        jPasswordContraUsuario.setText("jPasswordField2");
        jPasswordContraUsuario.setBorder(null);
        jPasswordContraUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordContraUsuarioMouseClicked(evt);
            }
        });
        jPanel4.add(jPasswordContraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 246, 180, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 352, 390));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 490, 450));

        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.setPreferredSize(new java.awt.Dimension(32, 32));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseReleased(evt);
            }
        });
        jPanel1.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimizar.setPreferredSize(new java.awt.Dimension(32, 32));
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseReleased
        // TODO add your handling code here:
        int res= JOptionPane.YES_NO_OPTION;
        int respuesta=JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir del programa?","Salir",res);
        if(respuesta==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelCerrarMouseReleased

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(SesionLogin.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jTextFieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioMouseClicked
        // TODO add your handling code here:
        this.jTextFieldUsuario.setText("");
    }//GEN-LAST:event_jTextFieldUsuarioMouseClicked

    private void jPasswordContraUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordContraUsuarioMouseClicked
        // TODO add your handling code here:
        this.jPasswordContraUsuario.setText("");
    }//GEN-LAST:event_jPasswordContraUsuarioMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        String cuenta,contraseña,parte1,parte2,query;
        cuenta=this.jTextFieldUsuario.getText().trim();
        query="select * from empleados where nombre= "+"'"+cuenta+"'";
        this.conn.Consult(query);
        try{
            String contraseñaMySql=this.conn.rs.getString(2);
            char[] passw=this.jPasswordContraUsuario.getPassword();
            contraseña=new String(passw);
            String contraseñaencriptada=DigestUtils.md5Hex(contraseña);
            if(contraseñaMySql.equals(contraseñaencriptada)){
                JOptionPane.showMessageDialog(this, "Bienvendio "+ this.conn.rs.getString(1)+" al sistema de Yummy Resorts","Bienvenida",1);
                setVisible(false);
                new MenuHotel().setVisible(true);
                //Generar un archivo con el usuario onlie y su informamcion
                //para el menu
                
            }else{
                JOptionPane.showMessageDialog(this, "Error en la contraseña, intentalo de nuevo");
            }
        
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "La cuenta ingresada no existe");
            //System.out.println("No existe la ceunta");
            
        }
       
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabelInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Presentacion().setVisible(true);
    }//GEN-LAST:event_jLabelInfoMouseClicked

    private void jLabelInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseExited
        // TODO add your handling code here:
        this.jLabelInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,51,51)));
    }//GEN-LAST:event_jLabelInfoMouseExited

    private void jLabelInfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseMoved
        // TODO add your handling code here:
        this.jLabelInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200,200,200)));
    }//GEN-LAST:event_jLabelInfoMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelCandadoIco;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelHotel;
    private javax.swing.JLabel jLabelIconoGrandeUsuario;
    private javax.swing.JLabel jLabelIconoLog;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordContraUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
    public void carga_iconos(){
        
        ImageIcon iconoUsuario=new ImageIcon("src/iconos/user_log.png");
        ImageIcon iconoCandado=new ImageIcon("src/iconos/padlock.png");
        ImageIcon iconoGrandeUsuario=new ImageIcon("src/iconos/user.png");
        ImageIcon iconoLogin =new ImageIcon("src/iconos/enter.png");
        ImageIcon iconoHotel=new ImageIcon("src/imagenes/yummy2.png");
        ImageIcon iconoMinimizar=new ImageIcon("src/iconos/minimize.png");
        ImageIcon iconoCerrar=new ImageIcon("src/iconos/cancel.png");
        ImageIcon iconoInfo=new ImageIcon("src/iconos/inf.png");
        
        this.jLabelIconoLog.setIcon(iconoUsuario);
        this.jLabelCandadoIco.setIcon(iconoCandado);
        this.jLabelIconoGrandeUsuario.setIcon(iconoGrandeUsuario);
        this.jButtonLogin.setIcon(iconoLogin);
        this.jLabelHotel.setIcon(iconoHotel);
        this.jLabelMinimizar.setIcon(iconoMinimizar);
        this.jLabelCerrar.setIcon(iconoCerrar);
        this.jLabelInfo.setIcon(iconoInfo);

    }


}



